apiVersion: v1
kind: ConfigMap
metadata:
  name: clahanstore-config
  namespace: clahanstore
data:
  MONGO_URI_USER: mongodb://mongodb:27017/userdb
  MONGO_URI_AUTH: mongodb://mongodb:27017/authdb
  MONGO_URI_PRODUCT: mongodb://mongodb:27017/productdb
  MONGO_URI_SEARCH: mongodb://mongodb:27017/searchdb
  MONGO_URI_INVENTORY: mongodb://mongodb:27017/inventorydb
  MONGO_URI_CART: mongodb://mongodb:27017/cartdb
  MONGO_URI_WISHLIST: mongodb://mongodb:27017/wishlistdb
  MONGO_URI_ORDER: mongodb://mongodb:27017/orderdb
  MONGO_URI_PAYMENT: mongodb://mongodb:27017/paymentdb
  MONGO_URI_INVOICE: mongodb://mongodb:27017/invoicedb
  MONGO_URI_SHIPPING: mongodb://mongodb:27017/shippingdb
  MONGO_URI_REVIEW: mongodb://mongodb:27017/reviewdb
  MONGO_URI_RECOMMENDATION: mongodb://mongodb:27017/recommendationdb
  MONGO_URI_ADMIN: mongodb://mongodb:27017/admindb
  USER_SERVICE_URL: http://user-service:3001
  AUTH_SERVICE_URL: http://auth-service:3002
  PRODUCT_SERVICE_URL: http://product-service:3003
  SEARCH_SERVICE_URL: http://search-service:3004
  INVENTORY_SERVICE_URL: http://inventory-service:3005
  CART_SERVICE_URL: http://cart-service:3006
  WISHLIST_SERVICE_URL: http://wishlist-service:3007
  ORDER_SERVICE_URL: http://order-service:3008
  PAYMENT_SERVICE_URL: http://payment-service:3009
  INVOICE_SERVICE_URL: http://invoice-service:3010
  SHIPPING_SERVICE_URL: http://shipping-service:3011
  REVIEW_SERVICE_URL: http://review-rating-service:3012
  RECOMMENDATION_SERVICE_URL: http://recommendation-service:3013
  ADMIN_SERVICE_URL: http://admin-service:3014
