apiVersion: v1
kind: Secret
metadata:
  name: clahanstore-secrets
  namespace: clahanstore
type: Opaque
stringData:
  MONGO_URI_USER: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/userdb"
  MONGO_URI_AUTH: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/authdb"
  MONGO_URI_PRODUCT: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/productdb"
  MONGO_URI_SEARCH: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/searchdb"
  MONGO_URI_INVENTORY: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/inventorydb"
  MONGO_URI_CART: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/cartdb"
  MONGO_URI_WISHLIST: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/wishlistdb"
  MONGO_URI_ORDER: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/orderdb"
  MONGO_URI_PAYMENT: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/paymentdb"
  MONGO_URI_INVOICE: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/invoicedb"
  MONGO_URI_SHIPPING: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/shippingdb"
  MONGO_URI_REVIEW: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/reviewdb"
  MONGO_URI_RECOMMENDATION: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/recommendationdb"
  MONGO_URI_ADMIN: "mongodb://mongodb.clahanstore.svc.cluster.local:27017/admindb"
  JWT_SECRET: "supersecretjwtkey_12345"
